---
title: "cleandatasetcreation"
format: pdf
editor: visual
author: Cooper Ruffing
---

```{r}

library(tidyverse)
library(readxl)
library(dplyr)
library(lubridate)
library(knitr)
library(writexl)
library(tibble)

attacks <- read_excel("attacks.xlsx")

injuries <- read_excel("injuries.xlsx")

area_percent <- read_excel("catchment_calculation_results.xlsx")

```

```{r}

attacks <- attacks |>
  select(-"period_id", -"period") |>
  mutate(period_start = as.POSIXct(period_start, tz = "UTC")) |>
  mutate(period_end = as.POSIXct(period_end, tz = "UTC"))


```

```{r}

injuries <- injuries |>
  select(-"period") |>
  mutate(period_start = as.POSIXct(period_start, tz = "UTC")) |>
  mutate(period_end = as.POSIXct(period_end, tz = "UTC"))

```

```{r}

area_percent <- area_percent |>
  filter(
     (`Segment Start` >= as.Date("2023-10-07") & `Segment Start` <= as.Date("2023-11-03") & Hospital == "Al Shifa Medical Hospital")
     |
       (`Segment Start` >= as.Date("2023-12-11") & `Segment Start` <= as.Date("2024-04-28") & Hospital == "European Hospital")
     |
       (`Segment Start` >= as.Date("2024-11-11") & `Segment Start` <= as.Date("2025-02-02") & Hospital == "Nasser Hospital")
  ) |>
  rename(period_start = `Segment Start`) |>
  rename(period_end = `Segment End`) |>
  mutate(percent_total_area = `Catchment Area (km²)`/365) |>
  mutate(period_start = as.POSIXct(period_start, tz = "UTC")) |>
  mutate(period_end = as.POSIXct(period_end, tz = "UTC"))

```

```{r}

renewed_dataset <- full_join(attacks, injuries, by = c("period_start", "period_end")) |>
  full_join(area_percent, by = c("period_start", "period_end"))

renewed_dataset[is.na(renewed_dataset)] <- 0

write_xlsx(dataset, "aggregated_dataset.xlsx")

```
